// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: iam/v1/iam.proto

package iam_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	v1 "github.com/olezhek28/microservices-course-examples/week_8/grpc_with_iam/shared/pkg/proto/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос Whoami
type WhoamiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"` // UUID активной сессии
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *WhoamiRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

// Ответ Whoami
type WhoamiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *v1.Session            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"` // Информация о текущей сессии
	User          *v1.User               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`       // Информация о пользователе, которому принадлежит сессия
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *WhoamiResponse) GetSession() *v1.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *WhoamiResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_iam_v1_iam_proto protoreflect.FileDescriptor

const file_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x10iam/v1/iam.proto\x12\x06iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16common/v1/common.proto\"2\n" +
	"\rWhoamiRequest\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\"c\n" +
	"\x0eWhoamiResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.common.v1.SessionR\asession\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.common.v1.UserR\x04user2`\n" +
	"\n" +
	"IAMService\x12R\n" +
	"\x06Whoami\x12\x15.iam.v1.WhoamiRequest\x1a\x16.iam.v1.WhoamiResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/whoamiBhZfgithub.com/olezhek28/microservices-course-examples/week_8/grpc_with_iam/shared/pkg/proto/iam/v1;iam_v1b\x06proto3"

var (
	file_iam_v1_iam_proto_rawDescOnce sync.Once
	file_iam_v1_iam_proto_rawDescData []byte
)

func file_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)))
	})
	return file_iam_v1_iam_proto_rawDescData
}

var (
	file_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_iam_v1_iam_proto_goTypes  = []any{
		(*WhoamiRequest)(nil),  // 0: iam.v1.WhoamiRequest
		(*WhoamiResponse)(nil), // 1: iam.v1.WhoamiResponse
		(*v1.Session)(nil),     // 2: common.v1.Session
		(*v1.User)(nil),        // 3: common.v1.User
	}
)

var file_iam_v1_iam_proto_depIdxs = []int32{
	2, // 0: iam.v1.WhoamiResponse.session:type_name -> common.v1.Session
	3, // 1: iam.v1.WhoamiResponse.user:type_name -> common.v1.User
	0, // 2: iam.v1.IAMService.Whoami:input_type -> iam.v1.WhoamiRequest
	1, // 3: iam.v1.IAMService.Whoami:output_type -> iam.v1.WhoamiResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_iam_v1_iam_proto_init() }
func file_iam_v1_iam_proto_init() {
	if File_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_v1_iam_proto_rawDesc), len(file_iam_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_iam_v1_iam_proto_depIdxs,
		MessageInfos:      file_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_iam_v1_iam_proto = out.File
	file_iam_v1_iam_proto_goTypes = nil
	file_iam_v1_iam_proto_depIdxs = nil
}
